export const items = [
    {
        "name":"Magic",
        "sku": 0,
        "storeName":"Buy Now",
        "img":"Tier F",
        "link": "https://checkout.square.site/merchant/5DXGGS1JY8G5J/checkout/UFOSCIA2GXSQU6A64MPQUQAU",
        "price": "$24.99",
        "new": false,
        "discount": false,
    },
    {
        "name":"Pokemon",
        "sku": 1,
        "storeName":"Buy Now",
        "img":"Tier: F",
        "link": "https://checkout.square.site/merchant/5DXGGS1JY8G5J/checkout/UFOSCIA2GXSQU6A64MPQUQAU",
        "price": "$24.99",
        "new": false,
        "discount": true,
    },
    {
        "name":"Star Wars",
        "sku": 2,
        "storeName":"Buy Now",
        "img":"Tier: F",
        "link": "https://checkout.square.site/merchant/5DXGGS1JY8G5J/checkout/UFOSCIA2GXSQU6A64MPQUQAU",
        "price": "$24.99",
        "new": false,
        "discount": false,
    },
    {
        "name":"Star Wars",
        "sku": 2,
        "storeName":"Buy Now",
        "img":"Tier: F",
        "link": "https://checkout.square.site/merchant/5DXGGS1JY8G5J/checkout/UFOSCIA2GXSQU6A64MPQUQAU",
        "price": "$24.99",
        "new": false,
        "discount": false,
    },
]